FROM debian:12-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt upgrade -y

RUN apt install -y --no-install-recommends coreutils less vim git rsync openssh-client wget curl python3 python3-venv

COPY ./builder /builder

WORKDIR /builder

RUN ./build_base.py

CMD ["/bin/bash"]

